version: '1.0'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    env_file:
      - .env
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - shipbubble-network

  api:
    build:
      context: "."
      dockerfile: Dockerfile.Dev
    restart: always
    ports:
      - 5500:5500
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - mysql
    env_file:
      - .env
    networks:
      - shipbubble-network

volumes:
  mysql:
    name: mysql

networks:
  shipbubble-network:
